### ISSUE TITLE
Performance issue on older NVIDIA GPUs using the python wheel

### ISSUE THREAD

**Issue by JoaoGuibs** [Di-Is/faiss-gpu-wheels#51]
First of all, thank you for publishing this up-to date wheel of the faiss library! 

I ran into a very specific issue by using the wheel published, essentially I observed a performance issue on older GPUs (gtx 1080ti) where the KNN brute-force distance computed with CPU and GPU is different for the same set of  vectors (same memory bank and query vector). 

I provide a script below to show case the difference of the knn distance computed with faiss CPU, faiss GPU and torch. As you can see the computed distances are not the same between faiss GPU and the other two. For this I used version 1.9.0 of the faiss wheel (CUDA 12) and python 3.10.

Do you have any idea what can be going on? Note that this error does not arrive in "newer" version GPUs (2080 rtx or 4070).

```import torch
import faiss
torch.manual_seed(42)

memory_bank = torch.rand((1000, 100))
dimension = memory_bank.shape[1]

def euclidean_dist(memory_bank, xq: torch.Tensor) -> torch.Tensor:
    xq_norm = xq.pow(2).sum(dim=-1, keepdim=True)  # |x|
    memory_bank_norm = memory_bank.pow(2).sum(dim=-1, keepdim=True)  # |y|
    # row distance can be rewritten as sqrt(|x| - 2 * x @ y.T + |y|.T)
    res = (
        xq_norm
        - 2 * torch.matmul(xq, memory_bank.transpose(-2, -1))
        + memory_bank_norm.transpose(-2, -1)
    )
    return res.clamp_min_(0)  # avoid small negative distances


def create_faiss_index(dimension, use_gpu=False):

    index = faiss.IndexFlatL2(dimension)

    if use_gpu:
        assert torch.cuda.is_available()
        gpu_resources = faiss.StandardGpuResources()
        gpu_options = faiss.GpuClonerOptions()
        gpu_options.device = 0
        index = faiss.index_cpu_to_gpu(
            gpu_resources, gpu_options.device, index, gpu_options
        )

    index.add(memory_bank)
    return index

x = torch.randn((1, 100))

cpu_index = create_faiss_index(dimension, use_gpu=False)

gpu_index = create_faiss_index(dimension, use_gpu=True)

distances, indices = cpu_index.search(x=x, k=1)
print("CPU distance: ", distances)

distances, indices = gpu_index.search(x=x, k=1)
print("GPU distance: ", distances)

distances = euclidean_dist(memory_bank, x)
print("Torch distance: ", distances.min())
```
The output being: 
`CPU distance:  [[117.63143]]
GPU distance:  [[9.947998]]
Torch distance:  tensor(117.6314)`

**Comment by Di-Is** [comment]
This is very strange behavior.
Could you please check the following two points to isolate the cause?

- Does this problem reproduce even if I install it using the official procedure? 
   - See https://github.com/facebookresearch/faiss/blob/main/INSTALL.md
- Also, do you get the same results with faiss-gpu-cu11 that I have published to PyPI?
   - See https://pypi.org/project/faiss-gpu-cu11/

**Comment by JoaoGuibs** [comment]
Thank you for the quick response @Di-Is . The problem does not reproduce if I change the Dockerfile from your code and use something based off of a ubuntu-based image (example below), but then it is not many_linux2_28 compliant. And regarding your second question, yes the output is the same with `faiss-gpu-cu11`

```
ARG CUDA_VERSION=12.4.1
ARG CUDNN_VERSION=cudnn8
# 61 for 1080TI
# 70 for TitanV
# 75 for Quadro RTX A 4000
# 86 for RTX A2000
# 89 for RTX 4060
ARG CUDA_ARCHITECTURE=61;70;75;86;89

from nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04 AS base-builder

ENV DEBIAN_FRONTEND=noninteractive

# pre-requisites for additional apt remotes
RUN apt-get update && \
    apt-get install -y ca-certificates gpg wget

# install shared build-kit
RUN apt-get update && apt-get install -y \
    software-properties-common \
    wget \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# Add Kitware APT repository and install CMake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/kitware.list \
    && apt-get update \
    && apt-get install -y cmake \
    && rm -rf /var/lib/apt/lists/*

# Install GCC 11
RUN apt-get install -y g++-11 gcc-11 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 10

# Set GCC 11 as default
RUN update-alternatives --config gcc && update-alternatives --config g++

RUN apt-get update && apt-get install -y make git libopenblas-dev liblapack-dev swig libgflags-dev gfortran

FROM base-builder as faiss-builder

COPY ./faiss /tmp/project/faiss
COPY ./patch/add-gpu-install.patch /tmp/project/patch/add-gpu-install.patch
WORKDIR /tmp/project

# # apply patch (assume build context is project root)

RUN git apply patch/add-gpu-install.patch

SHELL ["/bin/bash", "-c"]
ARG FAISS_OPT_LEVEL="generic"
ARG FAISS_ENABLE_GPU="ON"
ARG FAISS_ENABLE_RAFT="OFF"
ARG BUILD_NJOB=32

ARG CUDA_ARCHITECTURES="60;61;70;80;90"
RUN cd faiss \
 && cmake . \
       -B build \
       -DFAISS_ENABLE_GPU=${FAISS_ENABLE_GPU} \
       -DFAISS_ENABLE_RAFT=${FAISS_ENABLE_RAFT} \
       -DFAISS_ENABLE_PYTHON=OFF \
       -DBUILD_TESTING=OFF \
       -DFAISS_OPT_LEVEL=${FAISS_OPT_LEVEL} \
       -DCMAKE_BUILD_TYPE=Release \
       -DMKL_LIBRARIES=-lopenblas \
       -DCMAKE_C_COMPILER=/usr/bin/gcc-11 \
       -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 \
       -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES} \
  && make -C build -j${BUILD_NJOB} \
  && make -C build install


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
		  python3-dev \
		  python3-pip

RUN python3 -m pip install --upgrade --no-cache-dir pip

RUN pip3 install --upgrade --no-cache-dir \
	setuptools \
	wheel \
    auditwheel \
    patchelf
```

**Comment by Di-Is** [comment]
Thanks for the experiment!
The version of CUDA does not seem to matter, as it is reproduced in `faiss-gpu-cu11`.

If the CMAKE_CUDA_ARCHITECTURES in the provided Dockerfile is modified as follows, will any issues occur?

```Dockerfile
ARG CUDA_ARCHITECTURES=”60;70;80;90”
# or
ARG CUDA_ARCHITECTURES=”60-real;70-real;80-real;90-real”
```

**Comment by Di-Is** [comment]
After various investigations, I found that updating the CUDA Toolkit to version 12.2 produces correct calculation results on Pascal architecture GPUs (e.g., P4 in a GCP instance).

However, I am hesitant to update CUDA to address the issue you reported.
This is because it would be difficult for me to test on GPUs of different architectures and to handle similar issues that might arise in the future.

The faiss-gpu package distributed in the original repository is built with CUDA 11.4 and CUDA 12.1.
The CUDA 12.1 build does not support Pascal architecture GPUs.
I am inclined to align with the original repository and drop support for Pascal architecture GPUs.

**Comment by JoaoGuibs** [comment]
Indeed you are right, I updated the CUDA version to 12.2 and the results are consistent now! And I understand your decision to not support older architectures. Thanks!
